version: "3.6"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 3000

  kafka:
    image: confluentinc/cp-kafka
    hostname: kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka_ui:
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - kafka
    ports:
      - 8080:8080
    environment:
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092

  mysql:
    image: mysql:5.7.37
    container_name: "mysql"
    ports:
      - "3306:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --explicit_defaults_for_timestamp
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - "/Users/zouchen/mysql/db:/var/lib/mysql"
      - "/Users/zouchen/mysql/conf:/etc/mysql"
      - "/Users/zouchen/mysql/log:/var/log/mysql"

#  redis:
#    container_name: dev_redis
#    restart: always
#    ports:
#      - 6379:6379
#    build:
#      context: ./docker/redis
#      dockerfile: Dockerfile
#    command: /bin/bash -c "redis-server /app/redis.conf"
#
#  mariadb:
#    image: mariadb:10.3.20
#    ports:
#      - "3808:3808"
#      - "3306:3306"
#    environment:
#      - MARIADB_USER=mariadb
#      - MARIADB_PASSWORD=1qaz@WSX
#      - MARIADB_ROOT_PASSWORD=1qaz@WSX
#    volumes:
#      - "/Users/ray/mysql/db:/var/lib/mysql"
#      - "/Users/ray/mysql/conf:/etc/mysql"
