export const ERROR_CODE_NULL = 400
export const ERROR_CODE_TENANT_NOT_FOUND = 401
export const ERROR_CODE_USER_NOT_FOUND = 402
export const ERROR_CODE_PASSWORD_ERROR = 403
export const ERROR_CODE_TENANT_ENABLED = 404
export const ERROR_CODE_USER_ENABLED = 405
export const ERROR_CODE_TOKEN_ENABLED = 406
